alias a='sail artisan'
alias c='sail composer'
alias bs='browser-sync start --config'
alias n='sail npm'
alias fseed='sail artisan migrate:fresh && sail artisan db:seed'
alias fseedtest='sail artisan migrate:fresh --env=testing && sail artisan db:seed --env=testing'
alias spest='sail pest'
